clear;
clc;

list_patients = { ...
    'pat_102', ...
    'pat_7302', ...
    'pat_8902', ...
    'pat_11002', ...
    'pat_16202', ...
    'pat_21902', ...
    'pat_21602', ...
    'pat_22602', ...
    'pat_23902', ...
    'pat_26102', ...
    'pat_30002', ...
    'pat_30802', ...
    'pat_32502', ...
    'pat_32702', ...
    'pat_45402', ...
    'pat_46702', ...
    'pat_55202', ...
    'pat_56402', ...
    'pat_58602', ...
    'pat_59102', ...
    'pat_75202', ...
    'pat_79502', ...
    'pat_85202', ...
    'pat_92102', ...
    'pat_93902', ...
    'pat_96002', ...
    'pat_103002', ...
    'pat_109502', ...
    'pat_111902', ...
    'pat_114902'};

for p=1:numel(list_patients)

% Parameters
patient_id = list_patients{p};
data_dir = '/Volumes/My Passport/Workspace/data/epilepsiae';
segment_sec = 5; % in seconds

% Record location
patient_dir = [data_dir, '/', patient_id];
selectfile = 'selectfilelist_all.txt';
seizuremetafile = 'seizurefilelist.txt';

fid = fopen([patient_dir,'/',selectfile]);
file_list = textscan(fid, '%s');
fclose(fid);

file_list = file_list{1};
data_list = strrep(file_list, '.data', '.mat');
flat_signal_list = strrep(file_list, '.data', '_flat_signal_idx.mat');
save_list = strrep(file_list, '.data', '_flat_signal_segment_idx.mat');

for d=1:numel(file_list)
    disp(['Get flat signal segment index from file ' , file_list{d} ,' ...']);
    
    % Get the segment indices of flat signals
    load([patient_dir,'/',flat_signal_list{d}]);
    
    if numel(flat_signal_idx) > 0
        flat_signal_segment_idx = cell(numel(flat_signal_idx), 1);
        for i=1:numel(flat_signal_idx)
            idx = flat_signal_idx{i};
            start_flat_seg_idx = ceil(idx(1) / (sample_freq * segment_sec));
            end_flat_seg_idx = ceil(idx(end) / (sample_freq * segment_sec));
            flat_signal_segment_idx{i} = start_flat_seg_idx:end_flat_seg_idx;
        end
    else
        flat_signal_segment_idx = {};
    end
    
    disp(['Number of flat signal segments: ', num2str(numel(flat_signal_segment_idx))])
    for j=1:numel(flat_signal_segment_idx)
        disp(['[', num2str(flat_signal_segment_idx{j}(1)), ', ', ...
              num2str(flat_signal_segment_idx{j}(end)),']']);
    end
    
    save_fname = [patient_dir,'/',save_list{d}];
    save(save_fname, 'flat_signal_segment_idx', 'segment_sec', 'sample_freq');
end

end

















