function sparseAutoencoder = sparseAutoencoderTrain(inputSize, hiddenSize, ...
							lambda, sparsityParam, beta, X, minFuncOptions)
	theta = sparseAutoencoderInitializeParameters(inputSize, hiddenSize);
	if strcmp(minFuncOptions.Method,'lbfgs')
		[optTheta, cost] = minFunc( @(p) sparseAutoencoderCost(p,...
			inputSize, hiddenSize, lambda, sparsityParam, beta, X),...
			theta, minFuncOptions);
		sparseAutoencoder.optTheta = optTheta;
	elseif strcmp(minFuncOptions.Method,'sgd')
		[optTheta, cost] = sgd( @(p,D) sparseAutoencoderCost(p,...
			inputSize, hiddenSize, lambda, sparsityParam, beta, D),...
			theta, minFuncOptions, X, false);
		sparseAutoencoder.optTheta = optTheta;
	end
end